scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: angle_bounds
      type: laser_filters/LaserScanAngularBoundsFilter
      params:
        lower_angle: -3.141592653589793
        upper_angle: 3.141592653589793
    filter2:
      name: range
      type: laser_filters/LaserScanRangeFilter
      params:
        use_message_range_limits: false
        lower_threshold: 0.08
        upper_threshold: 12.0
        lower_replacement_value: .inf
        upper_replacement_value: .inf
